CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE classification (
    classificationid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    classificationart character varying(50) NOT NULL,
    classificationtype character varying(10) NOT NULL,
    CONSTRAINT "PK_classification" PRIMARY KEY (classificationid)
);

CREATE TABLE crew (
    crewid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    crewvalue character varying(20) NULL,
    CONSTRAINT "PK_crew" PRIMARY KEY (crewid)
);

CREATE TABLE position (
    positionid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    positiontitle character varying(50) NOT NULL,
    positionprefix character varying(10) NULL,
    positionshort character varying(10) NULL,
    CONSTRAINT "PK_position" PRIMARY KEY (positionid)
);

CREATE TABLE role (
    roleid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    roletitle character varying(50) NOT NULL,
    CONSTRAINT "PK_role" PRIMARY KEY (roleid)
);

CREATE TABLE engine (
    engineid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    enginenumber character varying(7) NULL,
    engineps integer NULL,
    enginecapacityccm integer NULL,
    enginecylinder integer NULL,
    engineconstructionyear integer NOT NULL,
    enginelength integer NOT NULL,
    enginewidth integer NOT NULL,
    enginehight integer NOT NULL,
    enginebody character varying(50) NULL,
    enginechassis character varying(50) NULL,
    engineisdeprecated boolean NOT NULL DEFAULT FALSE,
    enginelicenseplate character varying(12) NOT NULL,
    engineradiocall character varying(50) NULL,
    classificationid integer NOT NULL,
    crewid integer NOT NULL,
    CONSTRAINT "PK_engine" PRIMARY KEY (engineid),
    CONSTRAINT "FK_engine_classification_classificationid" FOREIGN KEY (classificationid) REFERENCES classification (classificationid) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT "FK_engine_crew_crewid" FOREIGN KEY (crewid) REFERENCES crew (crewid) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE client (
    clientid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    clientname character varying(50) NOT NULL,
    clientprename character varying(50) NOT NULL,
    clientsurname character varying(50) NOT NULL,
    clientpasswordhash character varying(256) NOT NULL,
    clientpasswordsalt character varying(128) NOT NULL,
    roleid integer NULL,
    positionid integer NULL,
    CONSTRAINT "PK_client" PRIMARY KEY (clientid),
    CONSTRAINT "FK_client_position_positionid" FOREIGN KEY (positionid) REFERENCES position (positionid) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT "FK_client_role_roleid" FOREIGN KEY (roleid) REFERENCES role (roleid) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX "IX_client_positionid" ON client (positionid);

CREATE INDEX "IX_client_roleid" ON client (roleid);

CREATE INDEX "IX_engine_classificationid" ON engine (classificationid);

CREATE INDEX "IX_engine_crewid" ON engine (crewid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20191027152748_InitialCreate', '3.0.0');

