--
-- PostgreSQL database dump
--

-- Dumped from database version 10.10
-- Dumped by pg_dump version 10.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'SQL_ASCII';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS fire;
--
-- Name: fire; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE fire WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';


ALTER DATABASE fire OWNER TO admin;

\connect fire

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO admin;

--
-- Name: classification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.classification (
    classificationid integer NOT NULL,
    classificationart character varying(50) NOT NULL,
    classificationtype character varying(10) NOT NULL
);


ALTER TABLE public.classification OWNER TO admin;

--
-- Name: classification_classificationid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.classification ALTER COLUMN classificationid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classification_classificationid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    clientid integer NOT NULL,
    clientname character varying(50) NOT NULL,
    clientprename character varying(50) NOT NULL,
    clientsurname character varying(50) NOT NULL,
    clientpasswordhash character varying(256) NOT NULL,
    clientpasswordsalt character varying(128) NOT NULL,
    clientrole character varying(100) NOT NULL,
    clientposition character varying(100)
);


ALTER TABLE public.client OWNER TO admin;

--
-- Name: client_clientid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN clientid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_clientid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crew; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.crew (
    crewid integer NOT NULL,
    crewvalue character varying(20) NOT NULL
);


ALTER TABLE public.crew OWNER TO admin;

--
-- Name: crew_crewid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.crew ALTER COLUMN crewid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crew_crewid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: engine; Type: TABLE; Schema: public; Owner: postgres
--weiter ab hier

CREATE TABLE public.engine (
    engineid integer NOT NULL,
    enginenumber character varying(7),
    engineps integer,
    enginecapacityccm integer,
    enginecylinder integer,
    engineconstructionyear integer NOT NULL,
    enginelength integer NOT NULL,
    enginewidth integer NOT NULL,
    enginehight integer NOT NULL,
    enginebody character varying(50),
    enginechassis character varying(50),
    engineisdeprecated boolean NOT NULL,
    enginelicenseplate character varying(12) NOT NULL,
    engineradiocall character varying(50),
    classificationid integer NOT NULL,
    crewid integer NOT NULL
);


ALTER TABLE public.engine OWNER TO admin;

--
-- Name: engine_engineid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.engine ALTER COLUMN engineid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.engine_engineid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: classification PK_classification; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classification
    ADD CONSTRAINT "PK_classification" PRIMARY KEY (classificationid);


--
-- Name: client PK_client; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT "PK_client" PRIMARY KEY (clientid);


--
-- Name: crew PK_crew; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.crew
    ADD CONSTRAINT "PK_crew" PRIMARY KEY (crewid);


--
-- Name: engine PK_engine; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.engine
    ADD CONSTRAINT "PK_engine" PRIMARY KEY (engineid);


--
-- Name: IX_engine_classificationid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_engine_classificationid" ON public.engine USING btree (classificationid);


--
-- Name: IX_engine_crewid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_engine_crewid" ON public.engine USING btree (crewid);


--
-- Name: engine FK_engine_classification_classificationid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.engine
    ADD CONSTRAINT "FK_engine_classification_classificationid" FOREIGN KEY (classificationid) REFERENCES public.classification(classificationid) ON DELETE CASCADE;


--
-- Name: engine FK_engine_crew_crewid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.engine
    ADD CONSTRAINT "FK_engine_crew_crewid" FOREIGN KEY (crewid) REFERENCES public.crew(crewid) ON DELETE CASCADE;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

